### ISSUE TITLE
Chrome Extension says maybe corrupted for no reason

### ISSUE THREAD

**Issue by Kikobeats** [kamranahmedse/githunt#37]
<img width="397" alt="Screenshot 2019-08-29 at 09 46 10" src="https://user-images.githubusercontent.com/2096101/63920795-e5499300-ca41-11e9-9ad3-de2982445855.png">

Hello,

I love love love GitHunt. A lot good good work is done here, so thank you for the dedication on the project 👏.

I normally consume GitHunt using the Chrome Extension. That's because, although I can configure the official site as tie first site to open on my browser, only using the extension make possible see GitHunt under a new tab.

However, for a time to now, I noted GitHunt it did not show under a new tab. When I enter on extensions, I see Chrome is saying it's "maybe corrupted" (WTF).

Any idea why this is happening?

**Comment by kamranahmedse** [comment]
Hey @Kikobeats, 

Thank you, I am glad you like the project :) 

I do not see this error. Could you please confirm if you are using the latest version of Chrome. Also, what happens if you click the Repair button? Maybe try removing and reinstalling the extension if it may help?

![image](https://user-images.githubusercontent.com/4921183/64072957-876ab480-cca8-11e9-974d-ee9d3cb7c9c9.png)

**Comment by Kikobeats** [comment]
I think my Chrome version is the last available

<img width="679" alt="Screenshot 2019-09-01 at 10 23 27" src="https://user-images.githubusercontent.com/2096101/64073770-9fd7d080-cca2-11e9-95ce-df4f6db299e3.png">

If I click on repair, then the extension is re-enabled, but it lost the api token

**Comment by kamranahmedse** [comment]
Yes, the local storage is lost upon the re-install which I think it did while repairing. However, I am glad you got it to work. I have published a newer version, do let me know if you face any issues. Thank you 🙏
